default:
  http_metas:
    content-type: text/html

  metas:
    title:        Manage Users and Groups
    robots:       index, follow
    description:  Manage Users and Groups
    keywords:     users, groups
    language:     en


  stylesheets: [style]
  javascripts: [script]

  has_layout:     on
  layout:         layout
