rendering: ~
web_debug: ~
security:  ~

# generally, you will want to insert your own filters here

snappsGlobal:
  class: snappsGlobalHTMLPathFilter

  
cache:     ~
common:    ~
flash:     ~
execution: ~

snapps:
  class: snappsFilter
