all:
    apps_name:      PORTFOLIO     
    page_heading:   Portfolio
    menu_name:      EmanPortfolio         
    email:
        smtp_mode:  true
        smtp_server:    58.185.30.163
        smtp_username:  
        smtp_password:  
        
        attachment_size_limit:  10
        
        from_default:           Micronclean Online
        from_address_default:   microncleanservice@micronclean.com.sg
        cclist:                 mcsloggerx@yahoo.com
        debug_address:          mcslogger@yahoo.com   
        debug_address_local:    mcslogger@yahoo.com  